### ISSUE TITLE
Ability to bind jmx to specific interfaces

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-jmx#1]
It seems there is no method to limit JMX to bind to specific IPs, need to add support for testing and restricting access via specific interface 

http://vafer.org/blog/20061010091658/

**Comment by slivne** [comment]
@amnonh this is the same behaviour of cassandra - it binds to all ips, ifo so we can close this

**Comment by amnonh** [comment]
This is the same as cassandra, we may want to change it in the future, so
we can keep it open and put it to some future version
