### ISSUE TITLE
Ubuntu 20.04 systemd install failure

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-jmx#110]
I know 20.04 is not supported
but install works, up until it comes to scylla-jmx:
```
Unpacking scylla-jmx (4.0.1-20200524.530232f8c19-1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-65xVuf/18-scylla-jmx_4.0.1-20200524.530232f8c19-1_all.deb (--unpack):
 unable to open '/usr/lib/systemd/system/scylla-jmx.service.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system
```

this is just FYI, since after that deb packaging seems to get broken beyond repair (above package cannot be removed, nothing else can be installed)
@syuu1228 ping

**Comment by tarzanek** [comment]
Workaround (and cleanup of above), if you don't mind having scylla-jmx:
```
apt -y remove scylla
apt -y install scylla-server
```

**Comment by avikivity** [comment]
Does it work on 18.04?

**Comment by tarzanek** [comment]
I can test 18.04, but I have no reason to believe it shouldn't, since 18.04 is supported

**Comment by tarzanek** [comment]
confirming, 18.04 just works, 20.04 doesn't, so this needs to be addressed before we will support 20.04

**Comment by tarzanek** [comment]
How to repro:
on 20.04 run:
```
sudo curl -o /etc/apt/sources.list.d/scylla.list -L <URL TO SCYLLA REPO>
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5e08fbd8b5d6ec9c

sudo apt-get update
sudo apt-get -y install scylla
```

**Comment by avikivity** [comment]
I did reproduce it; I don't understand why it happens.

**Comment by christianri** [comment]
Experiencing the same issue on a Debian 10.4 machine. The suggested workaround works, but leaves it without the nodetool utility then.

**Comment by avikivity** [comment]
I think I see it. 

```
root@a532ed454b8c:/xx# tar tvfa data.tar.xz 
drwxr-xr-x root/root         0 2015-08-24 09:22 ./
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/default/
-rw-r--r-- root/root       622 2015-08-24 09:22 ./etc/default/scylla-jmx
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/init/
-rw-r--r-- root/root       328 2015-08-24 09:22 ./etc/init/scylla-jmx.conf
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/systemd/
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/systemd/system/
drwxr-xr-x root/root         0 2015-08-24 09:22 ./etc/systemd/system/scylla-jmx.service.d/
-rw-r--r-- root/root        67 2015-08-24 09:22 ./etc/systemd/system/scylla-jmx.service.d/sysconfdir.conf
drwxr-xr-x root/root         0 2015-08-24 09:22 ./lib/
drwxr-xr-x root/root         0 2015-08-24 09:22 ./lib/systemd/
drwxr-xr-x root/root         0 2015-08-24 09:22 ./lib/systemd/system/
-rw-r--r-- root/root       459 2015-08-24 09:22 ./lib/systemd/system/scylla-jmx.service
```

should be /usr/lib, not /lib.

**Comment by toddwong** [comment]
In debian 10, `/lib` is a symbolic link to `/usr/lib`.

When dpkg unpack the files, it appends `.dpkg-new` to the file names.  After all file unpacked, it then renames then one by one, but after the renmaming of `/lib/systemd/system/scylla-jmx.service.dpkg-new`, there won't be `/usr/systemd/system/scylla-jmx.service.dpkg-new` any more.

But I know very little about the dpkg things. I don't know why scylla-server.deb, which seems having the same issue, works.

**Comment by avikivity** [comment]
@syuu1228 ping

**Comment by syuu1228** [comment]
@avikivity Seems like same bug fixed by https://github.com/scylladb/scylla-jmx/commit/2883a8dc63dca9944032143fb79ec3ae09a68ac1, but the commit seems like not backported to 4.0.1.

**Comment by avikivity** [comment]
I'll backport it.

**Comment by avikivity** [comment]
Closing as duplicate of scylladb/scylla#6010.
