### ISSUE TITLE
Scylla 4.2: Fail to build unified deb

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-jmx#120]
Similar to:
https://github.com/scylladb/scylla/issues/6736

Scylla 4.2 fails to build unified-deb
Looks like some issue with - and ~
https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/next/18/console

16:29:46  '../scylla-jmx_4.2.rc0-20200705.77d6f5e.orig.tar.gz' => '/jenkins/workspace/scylla-4.2/next/scylla-jmx/build/scylla-jmx-package.tar.gz'
16:29:46  This package has a Debian revision number but there does not seem to be
16:29:46  an appropriate original tar file or .orig directory in the parent directory;
16:29:46  (expected one of scylla-jmx_4.2~rc0-20200705.77d6f5e.orig.tar.gz, scylla-jmx_4.2~rc0-20200705.77d6f5e.orig.tar.bz2,
16:29:46  scylla-jmx_4.2~rc0-20200705.77d6f5e.orig.tar.lzma,  scylla-jmx_4.2~rc0-20200705.77d6f5e.orig.tar.xz or scylla-package.orig)

I guess this is also relevant to the tools-java repo (the next build step). Please verify.

**Comment by avikivity** [comment]
Backported to 4.2.
