### ISSUE TITLE
failed to reload nonroot.conf by `systemctl --user daemon-reload`

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-jmx#130]
version: unified-package-0.20200824.9636a3399.tar.gz

I manually changed /home/scylla-test/.config/systemd/user/scylla-jmx.service.d/nonroot.conf to workaround https://github.com/scylladb/scylla-jmx/issues/129, after modified the nonroot.conf, when I try to restart scylla-server or scylla-jmx, there is no reminder of reloading systemd config.

- `sed -ie 's/ExecStart=.*scylla-jmx /ExecStart=\/home\/scylla-test\/install_root\/jmx\/symlinks\/scylla-jmx /g' /home/scylla-  test/.config/systemd/user/scylla-jmx.service.d/nonroot.conf`

However, I tried to reload the config by `systemctl --user daemon-reload`, actually it doesn't work.

I changed the scylla-jmx path of ExecStart, but the result of `systemctl --user status scylla-jmx` didn't change.

```
● scylla-jmx.service - Scylla JMX
   Loaded: loaded (/home/scylla-test/.config/systemd/user/../../../install_root/etc/systemd/scylla-jmx.service; linked; vendor preset: enabled)
  Drop-In: /home/scylla-test/.config/systemd/user/scylla-jmx.service.d
           └─nonroot.conf
   Active: failed (Result: exit-code) since Tue 2020-08-25 22:19:49 UTC; 25s ago
  Process: 48818 ExecStart=/home/scylla-test/install_root/jmx/scylla-jmx $SCYLLA_JMX_PORT $SCYLLA_API_PORT $SCYLLA_API_ADDR $SCYLLA_JMX_ADDR $SCYLLA_JMX_FILE $SCYLLA_JMX_LOCAL $SCYLLA_JMX_REMOTE $SCYLLA_JMX_DEBUG (code=exited, status=200/CHDIR)
 Main PID: 48818 (code=exited, status=200/CHDIR)
```

/CC @syuu1228 @roydahan

**Comment by syuu1228** [comment]
What does ` I tried to reload the config by systemctl --user daemon-reload, actually it doesn't work.` means?
Is daemon-reload failed with some error message?
Or it just means scylla-jmx.service failed to start?
If it so, what was the error message of scylla-jmx.service?

**Comment by amoskong** [comment]
> What does ` I tried to reload the config by systemctl --user daemon-reload, actually it doesn't work.` means?
> Is daemon-reload failed with some error message?

No

> Or it just means scylla-jmx.service failed to start?

Yes

> If it so, what was the error message of scylla-jmx.service?

I tried again, but not reproduce.

Let's close this issue.
