### ISSUE TITLE
metrics: sstables_per_read_histogram returns number of sstables reads

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylla-jmx#199]
EstimatedHistogram, which is responsible for sstablesPerRead column
in SSTablesPerReadHistogram table histogram, returns values indicating 
the number of sstables reads instead of the number of sstables.

**Comment by mykaul** [comment]
We don't have the 'backport' candidate here - unsure what the process is later on, since we do wish to have this fix in earlier releases as well (do we update the submodule?).
@DoronArazii - need to follow up once this is merged.

**Comment by DoronArazii** [comment]
> @DoronArazii - need to follow up once this is merged.

It's in master --> https://github.com/scylladb/scylladb/commit/50ee4033a92e395e70c08e64d60667bb2681fd2b

**Comment by denesb** [comment]
> > @DoronArazii - need to follow up once this is merged.
> 
> It's in master --> [scylladb/scylladb@50ee403](https://github.com/scylladb/scylladb/commit/50ee4033a92e395e70c08e64d60667bb2681fd2b)

It is actually scylladb/scylladb@f82287a9afbdaeb87138a0918f05f4c52e9b5966.
