### ISSUE TITLE
Unimplemented methods in StorageService.java silently doing the wrong thing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla-jmx#23]
scylla-jmx's StorageService.java includes a dozen or so variants of the method forceAsyncRepair(). Each one takes a different combination of paramters, and supposed to call the generic repairAsync() function which takes a general option map.

However, some of these variants wrongly run repairAsync() with an empty option map, and some are even more broken, in that they don't even call repairAsync()!

Eventually we should correctly fix all these variants, as I did for one variant - forceRepairAsync(String keyspace, int parallelismDegree, Collection<String> dataCenters, Collection<String> hosts, boolean primaryRange, boolean fullRepair, String... columnFamilies).

But perhaps it is wiser to start with all the wrong variants throwing some sort of "unimplemented" exception - instead of silently doing the wrong thing, as they do now.

By the way, looking at other methods in the same file (StorageService.java), I see many other methods, not just forceRepair variants, doing the wrong thing. For example, we have

``` c++
    @Override
    public void takeMultipleColumnFamilySnapshot(String tag,
            String... columnFamilyList) throws IOException {
        // TODO Auto-generated method stub
        log(" takeMultipleColumnFamilySnapshot");
    }
```

User of this method will not know this was never actually implemented, and assume it worked correctly... I think all these methods should either be fixed, or be made to somehow report the fact that an unimplemented method was used.

**Comment by amnonh** [comment]
This was changed a long time ago now a call to the API that is not implemented get an unimplemented error from the API
