### ISSUE TITLE
scyla-jmx SLF4J errors

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-jmx#24]
When starting nodetool service on Scylla AMI 0.15 I get the following errors in the log:

```
Jan 12 08:33:35 ip-172-31-26-164 scylla-jmx[1792]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Jan 12 08:33:35 ip-172-31-26-164 scylla-jmx[1792]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Jan 12 08:33:35 ip-172-31-26-164 scylla-jmx[1792]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

nodetool seems to work fine, but we need to clean up this errors.

**Comment by syuu1228** [comment]
It's strange, because jar dependencies should be packaged in scylla-jmx-1.0.jar.
And even I added slf4j-simple-1.6.4.jar on classpath, still get same error.

**Comment by penberg** [comment]
I suspect we fixed this in commit 6692f5a3c0b1598ecee155a68c156bd26f7cd361. @tzach, do you still see the errors in logs?

**Comment by amnonh** [comment]
@tzach let's close this one

**Comment by tzach** [comment]
Done. You should look into the https://github.com/probot/stale to help clean this old tasks
