### ISSUE TITLE
scylla-jmx has significant GC activity when not used

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla-jmx#27]
There is no external load on scylla-jmx, but we can see in the GC log that there occur minor and major collections inducing pauses up to 200ms. 

This is probably caused by scylla-jmx polling scylla every second for some metrics even when not used.

```
1080.775: Application time: 0.2937128 seconds
1080.775: Total time for which application threads were stopped: 0.0001911 seconds, Stopping threads took: 0.0000178 seconds
1080.775: Application time: 0.0000257 seconds
1080.775: Total time for which application threads were stopped: 0.0000717 seconds, Stopping threads took: 0.0000089 seconds
1080.775: Application time: 0.0000209 seconds
1080.775: Total time for which application threads were stopped: 0.0000731 seconds, Stopping threads took: 0.0000084 seconds
1080.775: Application time: 0.0000132 seconds
1080.775: Total time for which application threads were stopped: 0.0000630 seconds, Stopping threads took: 0.0000062 seconds
1080.775: Application time: 0.0000136 seconds
1080.775: Total time for which application threads were stopped: 0.0000631 seconds, Stopping threads took: 0.0000062 seconds
1080.776: Application time: 0.0000350 seconds
1080.776: Total time for which application threads were stopped: 0.0000699 seconds, Stopping threads took: 0.0000063 seconds
1095.481: Application time: 14.7054517 seconds
1095.482: [Full GC (Allocation Failure)  237491K->30993K(253440K), 0.2362866 secs]
1095.718: Total time for which application threads were stopped: 0.2369596 seconds, Stopping threads took: 0.0000210 seconds
1097.718: Application time: 2.0001543 seconds
1097.718: Total time for which application threads were stopped: 0.0001689 seconds, Stopping threads took: 0.0000208 seconds
1110.482: Application time: 12.7636455 seconds
1110.483: [GC (Allocation Failure)  100945K->52084K(253440K), 0.0860028 secs]
1110.569: Total time for which application threads were stopped: 0.0868157 seconds, Stopping threads took: 0.0003010 seconds
1126.776: Application time: 16.2074052 seconds
1126.777: [GC (Allocation Failure)  122036K->71547K(253440K), 0.1061292 secs]
1126.883: Total time for which application threads were stopped: 0.1065841 seconds, Stopping threads took: 0.0000201 seconds
1142.778: Application time: 15.8951925 seconds
1142.778: [GC (Allocation Failure)  141499K->91035K(253440K), 0.1146070 secs]
1142.894: Total time for which application threads were stopped: 0.1155050 seconds, Stopping threads took: 0.0000227 seconds
1158.781: Application time: 15.8874965 seconds
1158.781: [GC (Allocation Failure)  160987K->110368K(253440K), 0.1066694 secs]
```

**Comment by nyh** [comment]
I don't know how polling something every 1 second can (in your pasted output) generate 70 MB of garbage every 15 seconds... Do we do something extremely inefficient on every such poll, like create a new thread or a new very large buffer, etc.?
But I have a somewhat-related question: Why do we give scyllajmx 250 MB of heap? Couldn't it settle with a lot less? The above output suggests roughly 30 MB is actually used. We could leave more memory to more productive use in scylladb, and if we gave Java a smaller heap, maybe GC pauses would be more frequent, but shorter?

**Comment by avikivity** [comment]
If you limit the heap too much, and you overflow it, the effects are disastrous.  So better to give too much than too little, and I can see it needing more when processing nodes with many tables or sstables.

The idea is that the JVM heap grows when needed, so if the full 256MB is not needed, it will collect sooner.  Maybe that's not happening, or maybe it did need the entire heap in the past, and now it can't shrink it.

**Comment by nyh** [comment]
@avikivity  you're right about limiting the heap size too much leading to a disaster, but it's sad to think that scyllajmx, which is more-or-less (and my apologies to the people who wrote it) a silly wrapper from the jmx protocol to our rest protocol - could ever need 256 MB of memory (Bill gates once said 640 KB should be enough for anybody ;-)).

Indeed the heap being 256 MB might indicate that at some point of the run, a smaller heap was not big enough. BUT, It can also indicate that this was the initial heap size: AFAIK, the default initial heap size is 1/64 of the machine's memory - so if you have 16 GB of memory, you'll get the default initial heap size as 256 MB... We can override this initial heap size with the "-Xms" option, and using it is safer than setting the maximum heap size (-Xmx) which has the dangers you mentioned.

By the way, In Sun's JVM (and decedents), a heap, once reaching a certain size, can never shrink. Under any circumstances.

**Comment by avikivity** [comment]
`-Xms` is certainly a good idea.

**Comment by avikivity** [comment]
I can't tell is 256MB is enough, but if it does need 30MB, then reducing it looks dangerous, I can see it needing 8X more memory in other circumstances.

**Comment by avikivity** [comment]
`-Xms` is a good idea.

**Comment by tzach** [comment]
@amnonh is this issue solved?

**Comment by amnonh** [comment]
Yup
