### ISSUE TITLE
README mistake?

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-jmx#4]
@amnonh 
Your instructions to run jmx-urchin are:
```
java -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar target/urchin-mbean-1.0.jar
```  
The README is just
```
java -jar target/urchin-mbean-1.0.jar
```

which is it?

**Comment by penberg** [comment]
AFAICT, this is fixed by https://github.com/scylladb/scylla-jmx/commit/197c8c7e05cf2dc9a6a2b3513df4afc20f9db67a. @tzach, can you please close the issue?
