### ISSUE TITLE
alternate port switch not being respected

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-jmx#41]
Tried to start jmx in a non-standard port. Option was ignored and we are listening to 7199 nevertheless.

```
$ java -jar target/scylla-jmx-1.0.jar -Dcassandra.jmx.local.port=7200
Connecting to http://localhost:10000
Starting the JMX server
JMX is not enabled to receive remote connections.
service:jmx:rmi://localhost/jndi/rmi://localhost:7199/jmxrmi
```

**Comment by slivne** [comment]
you are supposed to use the script scylla-jmx to run jmx and it has options
to support updating the change of the port (at least by scanning the script
I think it should be supported)

**Comment by glommer** [comment]
Through the script it works. Thanks @slivne 

So far I was always running jmx directly - never really used that script.
