### ISSUE TITLE
read parameters from configuration file

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-jmx#44]
Right now, if we want to  change the behavior of scylla-jmx, for example to accept remote connections, we need to change the systemd file itself.

That is both inconvenient and ugly by systemd standards. The best way to handle this is what we do in Scylla, using environment variables that are present in /etc/sysconfig/scylla-jmx.

The latter file already exists, but it is only passing some path variables. We should extend it to allow us to change scylla-jmx behavior (remote, ssl, auth, etc), through external configuration files.

**Comment by penberg** [comment]
Fixed by commit https://github.com/scylladb/scylla-jmx/commit/e80a5e3cb319fc80c669d6d75f5abeb0d781758b from @fdv.
