### ISSUE TITLE
wire up StorageServiceMean.forceTerminateAllRepairSessions

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-jmx#47]
scylladb/scylla@a59e375aadb0ab42eac8f69003cafa868cf9d99a implements the ability to terminate repair session - lets wire it up

**Comment by amnonh** [comment]
It's already wire up,
the jmx supported it all along but the API used to return not implemented, @asias patch connected the API which was the missing part.

Nothing todo.
@slivne this can be closed

**Comment by slivne** [comment]
did you test it ?

**Comment by amnonh** [comment]
I tested that it is wired, didn't test the repair mechanism.

I connect with jconsole and run the method of the mbean, and got in the traces:
 [shard 0] repair - Aborted 0 repair job(s)
