### ISSUE TITLE
scylla-jmx on centos does not provide a systemd service

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-jmx#6]
using head
Using head of scylla-jmx

[centos@ip-172-30-0-58 scylla-jmx]$ git log -1
commit 709bc37fcd955ad6ed0b1b53570b9bd88384272f
Author: Takuya ASADA <syuu@cloudius-systems.com>
Date:   Mon Sep 21 17:47:52 2015 +0300

    dist: use jre-1.8.0/bin/java instead of /usr/bin/java, since 1.8.0 is not default on CentOS
    
    Signed-off-by: Takuya ASADA <syuu@cloudius-systems.com>

built 

created rpm 
installed it

doing sudo systemctl | grep scylla does not show the scylla-jmx.service

**Comment by syuu1228** [comment]
@penberg Which command line option? I don't find it

**Comment by penberg** [comment]
@slivne This issue has been solved already, right? Please close.
