### ISSUE TITLE
relocatable package doesn't work out of the box

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-jmx#61]
There is a step needed to get scylla-jmx to work which is not done by our relocatable package (which does not have an install.sh script)

We need to create a link to the jvm into symlinks/scylla-jmx. Once that step is done manually everything works perfectly.

We should somehow have an easier way to do this, either by providing something that links to `$(which java)` by default, or having an install step , or both.

**Comment by syuu1228** [comment]
We tested it enough, can close now.
