### ISSUE TITLE
global latency metrics have wrong endpoint

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-jmx#68]
https://github.com/scylladb/scylla-jmx/blob/ca3fa8de208f6b39a06a6c6f74fd3a542d4cfaaa/src/main/java/org/apache/cassandra/metrics/TableMetrics.java#L42

line #44 and #45
LatencyMetrics("Write", compose("read_latency"),
LatencyMetrics("Range", compose("read_latency"),

should be 
LatencyMetrics("Write", compose("write_latency"),
LatencyMetrics("Range", compose("range_latency"),

- but then I lack info on those metrics, so can someone confirm if this is really a bug?

**Comment by tarzanek** [comment]
Hello @elcallio , can you please check above and if this is a bug I can send a patch, if not, just close this Q.
tia
L

**Comment by amnonh** [comment]
@tarzanek range_latency are not implemented, the use of read_latency is so that nodetool would work

**Comment by tarzanek** [comment]
ok, if it is a feature than I don't have a problem, perhaps a comment there would help
and perhaps LatencyMetrics("Write", compose("write_latency") - can be write_latency instead of read_latency
but I will leave it up to you @amnonh how to fix this, or feel free to close

**Comment by slivne** [comment]
closing this for now ...
