### ISSUE TITLE
The proxy need to cache some of the requests

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-jmx#8]
Some of the requests, like network topology tokens and nodes are used multiple times in a single nodetool command and they are not likely to change in a sort interval.

The end result is that the nodetool takes a long time, a simple solution would be to add a local cache for the APIClient, some request will be able to mark to cache the reply (with some reasonable TTL) This will speed up the nodetool performance with little change in the code

**Comment by amnonh** [comment]
It can be closed:
With patch
be8eea6bd4a350d0d9b6e30c6a84c5730a21ff93

**Comment by slivne** [comment]
@amnonh you can close an issue you have created :)
